
import {loadResearch,researchPlayer} from './research.js';
import {parseMarketText,evaluateProp} from './edge.js';
import {discoverBoard} from './edge5.js';
import {buildPrediction,bestBetGate} from './model6.js';
import {buildMatchupProfile,defensiveRankings} from './matchup7.js';

const S={page:'Matchup Board',season:2026,data:null,props:[],defenses:[],offenses:[],loading:true,q:'',minScore:55,market:'ALL'};
const app=document.querySelector('#app');
const esc=x=>String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const pct=x=>x==null?'—':`${(x*100).toFixed(1)}%`;
const pill=(x,c='info')=>`<span class="pill ${c}">${esc(x)}</span>`;
function cm(){return new Map((S.data.board||[]).map(p=>[p.playerId,researchPlayer(p.playerId,S.data.stats.data,S.data.games.data,S.data.injuries.data)]))}
function defense(team){return S.defenses.find(x=>(x.team||x.defteam)===team)||{}}
function offense(team){return S.offenses.find(x=>(x.team||x.posteam)===team)||{}}
function matchupFor(p){
 const ctx=S.data.board.find(x=>x.playerId===p.playerId)||{};
 const profile=buildMatchupProfile({defense:defense(p.opponent),offense:offense(p.team),weather:p.weather||{},spread:p.spread,total:p.total,player:ctx,market:p.market});
 return {...p,matchup:profile,matchupScore:profile.score};
}
function predictions(){const m=cm();return S.props.map(p=>{const ctx=S.data.board.find(x=>x.playerId===p.playerId)||{},r=m.get(p.playerId)||{},e=evaluateProp(p,r);const mp=matchupFor({...p,...e});const base=r.baseline?.[p.market]??r.season?.[p.market]??r.mean;const adjusted=Number.isFinite(Number(base))?Number(base)*mp.matchup.factor:null;const pred=buildPrediction({prop:{...p,...e},research:r,matchup:defense(p.opponent),injuries:S.data.injuries.data||[],player:ctx,calibrationRows:[]});const gate=bestBetGate({...pred,projection:adjusted??pred.projection,edge:e.edge,matchupScore:mp.matchupScore,quality:e.edge*7+e.confidence*.45,freshnessScore:1});return {...gate,...mp}}).sort((a,b)=>b.matchupScore-a.matchupScore)}
function render(){app.innerHTML=`<header class="topbar"><div class="brand">NFL <span>RESEARCH LAB</span></div><div class="status"><i class="dot"></i> Step 7 · Matchup intelligence</div></header><div class="layout"><aside><div class="label navtitle">MATCHUP ENGINE</div>${['Matchup Board','Defense Profiles','Coverage','Pressure & Pace','Game Script','Scenario Matchups','Methodology'].map(x=>`<button class="navbtn ${S.page===x?'active':''}" data-nav="${x}">${x}</button>`).join('')}<div class="footer">Step 7 · Transparent adjustments</div></aside><main class="main">${body()}</main></div>`;document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{S.page=b.dataset.nav;render()});document.querySelector('#refresh')?.addEventListener('click',load);document.querySelector('#query')?.addEventListener('input',e=>{S.q=e.target.value;render()});document.querySelector('#minScore')?.addEventListener('change',e=>{S.minScore=+e.target.value;render()})}
function head(k,t,s){return `<div class="hero"><div><div class="eyebrow">${k}</div><h1>${t}</h1><div class="muted">${s}</div></div><button class="btn primary" id="refresh">Refresh research</button></div>`}
function controls(){return `<div class="filters"><input id="query" class="control" placeholder="Player / team / market" value="${esc(S.q)}"><select id="minScore" class="control"><option value="50">Matchup score 50+</option><option value="55" ${S.minScore===55?'selected':''}>55+</option><option value="60">60+</option><option value="65">65+</option><option value="70">70+</option></select></div>`}
function table(rows){return `<div class="tablewrap"><table class="table"><thead><tr><th>Player</th><th>Market</th><th>Line</th><th>Side</th><th>Matchup</th><th>Projection</th><th>Edge</th><th>Drivers</th></tr></thead><tbody>${rows.map(x=>`<tr><td><b>${esc(x.player)}</b><div class="sub">${esc(x.team)} vs ${esc(x.opponent)}</div></td><td>${esc(x.market)}</td><td>${x.line}</td><td>${pill(x.bestSide,x.bestSide==='OVER'?'ok':'warn')}</td><td><b>${x.matchupScore.toFixed(0)}</b></td><td>${x.projection==null?'—':x.projection.toFixed(1)}</td><td>${Number(x.edge).toFixed(1)}pp</td><td class="why">${esc((x.matchup?.notes||[]).join(' • ')||'Neutral')}</td></tr>`).join('')}</tbody></table>${!rows.length?'<div class="empty">No matchup-qualified markets under the current filter.</div>':''}</div>`}
function board(){const rows=predictions().filter(x=>x.matchupScore>=S.minScore).filter(x=>`${x.player} ${x.team} ${x.opponent} ${x.market}`.toLowerCase().includes(S.q.toLowerCase()));return head('STEP 7 · MATCHUPS','Matchup Board','Opponent tendencies, coverage structure, pressure, pace, game script and weather now feed the research layer.')+`<div class="grid cards">${[['Markets',S.props.length],['Matchup qualified',rows.length],['Defenses loaded',S.defenses.length],['Best score',rows.length?rows[0].matchupScore.toFixed(0):'—']].map(x=>`<div class="card"><div class="label">${x[0]}</div><div class="num">${x[1]}</div></div>`).join('')}</div><div class="panel"><div class="panelhead"><h2>Matchup-adjusted board</h2>${controls()}</div>${table(rows)}</div>`}
function defenses(){const r=defensiveRankings(S.defenses);return head('DEFENSE PROFILES','Defensive Matchup Rankings','Separate pass defense, run defense and pressure rather than using one generic defensive rank.')+`<div class="panel"><div class="tablewrap"><table class="table"><thead><tr><th>Team</th><th>Pass score</th><th>Run score</th><th>Pressure</th><th>EPA/play</th><th>Man</th><th>Zone</th><th>Blitz</th></tr></thead><tbody>${r.map(x=>`<tr><td><b>${esc(x.team)}</b></td><td>${x.passScore.toFixed(0)}</td><td>${x.runScore.toFixed(0)}</td><td>${x.pressureScore.toFixed(0)}</td><td>${x.epaPerPlay.toFixed(3)}</td><td>${(x.manRate*100).toFixed(1)}%</td><td>${(x.zoneRate*100).toFixed(1)}%</td><td>${(x.blitzRate*100).toFixed(1)}%</td></tr>`).join('')||'<tr><td colspan="8">No defense feed loaded.</td></tr>'}</tbody></table></div></div>`}
function coverage(){return head('COVERAGE','Coverage Structure','Coverage type and man/zone tendencies are treated as modest context, not deterministic player outcomes.')+`<div class="grid two">${S.defenses.slice(0,20).map(x=>`<div class="panel"><h2>${esc(x.team)}</h2><div class="metrics"><div><span>Man</span><b>${(Number(x.manRate||0)*100).toFixed(0)}%</b></div><div><span>Zone</span><b>${(Number(x.zoneRate||0)*100).toFixed(0)}%</b></div><div><span>C1</span><b>${(Number(x.cover1||0)*100).toFixed(0)}%</b></div><div><span>C3</span><b>${(Number(x.cover3||0)*100).toFixed(0)}%</b></div></div></div>`).join('')||'<div class="empty">Load participation/coverage data to populate this page.</div>'}</div>`}
function pressure(){return head('PRESSURE & PACE','Pressure, Pace & Volume','These variables can shift opportunity volume before the player-specific projection is priced.')+`<div class="grid two">${S.defenses.slice(0,20).map(x=>`<div class="panel"><h2>${esc(x.team)}</h2><p>Pressure: <b>${(Number(x.pressureRate||0)*100).toFixed(1)}%</b></p><p>Blitz: <b>${(Number(x.blitzRate||0)*100).toFixed(1)}%</b></p><p>Seconds/play: <b>${Number(x.pace||0).toFixed(1)}</b></p></div>`).join('')||'<div class="empty">No defensive environment feed loaded.</div>'}</div>`}
function script(){return head('GAME SCRIPT','Spread / Total / Volume','Expected game script can influence passing, rushing and total opportunity. The adjustment is intentionally capped.')+`<div class="panel"><h2>Script rules</h2><ul><li>Favorites can receive a modest rushing-volume boost in positive scripts.</li><li>Large underdogs can receive a modest passing-volume boost.</li><li>High totals increase volume modestly; low totals reduce it modestly.</li><li>These are context adjustments, not predictions of exact score.</li></ul></div>`}
function scenario(){return head('SCENARIO MATCHUPS','What-If Matchup Lab','Production adapters can pass alternate opponent, spread, total and weather inputs without changing the core player model.')+`<div class="grid two"><div class="panel"><h2>Example scenarios</h2><p>• Starter inactive → projected role rises.</p><p>• Defense shifts to heavier man coverage → receiver matchup modifier changes.</p><p>• High-pressure opponent → passing distribution shifts.</p><p>• Strong wind → passing/receiving projection is reduced.</p></div><div class="panel"><h2>Guardrail</h2><p>Every modifier is bounded. The app shows the reasons behind an adjustment so the user can audit it.</p></div></div>`}
function method(){return head('METHODOLOGY','Step 7 Architecture','Step 7 connects matchup intelligence to Step 6 without hiding the assumptions.')+`<div class="grid two"><div class="panel"><h2>Inputs</h2><ul><li>Defensive EPA and success rate</li><li>Pressure and blitz rate</li><li>Man/zone and coverage shell</li><li>Offensive pace/pass rate</li><li>Spread and game total</li><li>Weather / roof</li><li>Player position and role</li></ul></div><div class="panel"><h2>Data support</h2><p>nflverse participation documents offense/defense personnel, defenders in the box, pass rushers, pressure, routes, man/zone and coverage type. PBP provides the game/play context needed to aggregate those signals.</p><p class="muted">Participation from 2023 onward is supplied after the season rather than updating live, so live production should prefer currently updating feeds for any feature that depends on same-week participation.</p></div></div>`}
function body(){if(S.loading)return `<div class="empty"><div class="spinner"></div><h2>Loading Step 7 matchup layer…</h2></div>`;if(!S.data)return `<div class="empty">Research unavailable. <button class="btn primary" id="refresh">Retry</button></div>`;return ({'Matchup Board':board,'Defense Profiles':defenses,'Coverage':coverage,'Pressure & Pace':pressure,'Game Script':script,'Scenario Matchups':scenario,'Methodology':method}[S.page]||board)()}
async function load(){S.loading=true;render();try{S.data=await loadResearch(S.season);S.defenses=S.data.defenses?.data||S.data.defenses||[];S.offenses=S.data.offenses?.data||S.data.offenses||[]}catch(e){S.data=null}S.loading=false;render()}
render();load();
